stages:
  - build
  - packaging
  - release
  - deploy

build:update-dependencies:
  stage: build
  tags:
    - arch
    - dockerbuild
  when: manual
  image: docker
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t rts .
    - docker tag rts:latest registry.gitlab.com/epitech-it-2027/rts/rts-env:latest
    - docker push registry.gitlab.com/epitech-it-2027/rts/rts-env:latest

build:project:
  stage: build
  image: registry.gitlab.com/epitech-it-2027/rts/rts-env:latest
  tags:
    - arch
    - dockerbuild
  script:
    - cd network
    - cp -r /usr/app/build .
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    #- cmake --build .
    - make -j8
  artifacts:
    paths:
      - network/r-type_server
      - network/r-type_client
    expire_in: 1 day

build:windows:
  stage: build
  tags:
    - windows
  when: manual
  script:
    - echo "Setting up Conan profile for MSVC"
    - conan profile detect --force

    - echo "Installing dependencies with Conan"
    - cd network
    - conan install . --output-folder=build --build=missing

    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release

  artifacts:
    paths:
      - ${BUILD_DIR}/Release
    expire_in: 1 day
  allow_failure: true

build-delivery:
  stage: packaging
  needs:
    - build:project
  when: manual
  tags:
    - dockerbuild
  script:
    - docker build -t rts .
